const SAVE_KEY="staticquasar931_epstein_clicker_save_v4";
const WARNING_KEY="staticquasar931_epstein_clicker_hide_warning_v1";
const SCORE_STEP=10n;
const AUTO_TICKS_PER_SEC=20n;
const BASE_PER_CLICK=1n;
const BUY_MODES=[1n,10n,100n];
const TOTAL_LEVELS=500;
const LEVEL_PREVIEW_COUNT=30;
const MAX_STEPS=4096;

const LEVEL_NAMES=["Witness List","Midnight Ledger","Velvet Blackmail Ring","Crimson Passport","Ironclad Alibi","Ghost Manifest","Silent Airstrip","Closed Circle","Hidden Client List","Dark Money Vault","Influence Laundering Network","Private Archive","Obsidian Contact Grid","Immunity Broker","Deep State Switchboard","Cipher Estate","Black Budget Engine","Executive Escape Route","Phantom Holdings","Sovereign Coverup","Global Pressure Machine","Velvet Authority","The Inner Circle","No Witness Protocol","Eternal Immunity","Final Cover Story","Apex Control Matrix","World Silence Grid","Untouchable Dynasty","Last Alibi","Absolute Override","Obsidian Network","Phantom Array","Blackmail Engine","Immunity Protocol","Shadow Directive","Sovereign Authority","Cipher Core","Final Alibi","Inner Circle Engine","No Witness Override","Global Silence Force","Absolute Control Grid","Dark Ledger Protocol","Eternal Coverup","Apex Immunity","Costco Business Membership","Standing Baby Oil Card"];
const SKINS=[["epstein","Epstein","click.png"],["mrbeast","MrBeast","https://cdn.jsdelivr.net/gh/StaticQuasar931/Wheres-Epstein@main/Assets/Waldos/Special/mb1.png"],["kim","Kim Jong Un","https://cdn.jsdelivr.net/gh/StaticQuasar931/Wheres-Epstein@main/Assets/Waldos/Special/kju1.png"],["musk","Elon Musk","https://cdn.jsdelivr.net/gh/StaticQuasar931/Wheres-Epstein@main/Assets/Waldos/Special/mus1.png"],["diddy","Diddy","https://cdn.jsdelivr.net/gh/StaticQuasar931/Wheres-Epstein@main/Assets/Waldos/advanced/di1.png"],["trump","Trump","https://cdn.jsdelivr.net/gh/StaticQuasar931/Wheres-Epstein@main/Assets/Waldos/trum1.png"],["hawking","Stephen Hawking","https://cdn.jsdelivr.net/gh/StaticQuasar931/Wheres-Epstein@main/Assets/Waldos/steph1.png"],["epstein2","Epstein 2","https://cdn.jsdelivr.net/gh/StaticQuasar931/Wheres-Epstein@main/Assets/Waldos/eps1.png"]];
const UPGRADES=[
["cursor","Cursor",1000n,10n,125n],["diddy","Diddy Factory",8000n,25n,130n],["mega","Mega Factory",15000n,50n,135n],["oil","Baby Oil Factory",40000n,150n,135n],["degree","Epstein Degree",80000n,400n,135n],["nyc","NYC Apartment",500000n,2000n,135n],["mex","Mexico House",3000000n,15000n,135n],["island","Epstein Island",15000000n,80000n,135n],["jet","Gulfstream Jet",80000000n,400000n,135n],["runway","Private Island Runway",500000000n,2500000n,135n],["shell","Shell Company Empire",3000000000n,15000000n,135n],["offshore","Offshore Money Network",20000000000n,100000000n,135n],["media","Media Control Machine",150000000000n,750000000n,135n],["lobby","Global Lobbying Force",1000000000000n,5000000000n,135n],["access","Shadow Access Pass",8000000000000n,40000000000n,135n],["grid","World Influence Grid",60000000000000n,300000000000n,135n],["protocol","Reality Protocol",500000000000000n,2500000000000n,135n],["final","The Untouchable",4000000000000000n,20000000000000n,135n],["cabal","The Cabal Engine",20000000000000000n,100000000000000n,125n],["sing","Singularity Core",100000000000000000n,500000000000000n,125n],["vault","Black Vault Network",500000000000000000n,2500000000000000n,125n],["oracle","Oracle Array",2500000000000000000n,12500000000000000n,125n],["zeit","Zeit Control",12500000000000000000n,62500000000000000n,125n],["rift","Rift Generator",62500000000000000000n,312500000000000000n,125n],["dynasty","Dynasty Protocol",312500000000000000000n,1562500000000000000n,125n],["omega","Omega Directive",1562500000000000000000n,7812500000000000000n,125n],["eclipse","Eclipse Authority",7812500000000000000000n,39062500000000000000n,125n],["godmode","Godmode Override",39062500000000000000000n,195312500000000000000n,125n],["infinite","Infinite Stage",195312500000000000000000n,976562500000000000000n,125n],["ledger","Midnight Ledger",976562500000000000000000n,4882812500000000000000n,125n],["velvet","Velvet Blackmail Ring",4882812500000000000000000n,24414062500000000000000n,125n],["passport","Crimson Passport",24414062500000000000000000n,122070312500000000000000n,125n],["alibi","Ironclad Alibi",122070312500000000000000000n,610351562500000000000000n,125n],["airstrip","Silent Airstrip",610351562500000000000000000n,3051757812500000000000000n,125n],["circle","The Inner Circle",3051757812500000000000000000n,15258789062500000000000000n,125n],["witness","No Witness Override",15258789062500000000000000000n,76293945312500000000000000n,125n],["override","Absolute Override",76293945312500000000000000000n,381469726562500000000000000n,125n],["costco","Costco Business Membership",381469726562500000000000000000n,1907348632812500000000000000n,125n],["card","Standing Baby Oil Card",1907348632812500000000000000000n,9536743164062500000000000000n,125n]
];

const $=id=>document.getElementById(id);
const el={score:$("score"),perClick:$("perClick"),perSec:$("perSec"),upgradeCount:$("upgradeCount"),pageTitle:$("pageTitle"),safeModeBadge:$("safeModeBadge"),subjectHeading:$("subjectHeading"),clickBtn:$("clickBtn"),skinSelect:$("cloakSelect"),safeToggle:$("safeModeToggle"),buyAll:$("buyAllBtn"),buy1:$("buyMode1Btn"),buy10:$("buyMode10Btn"),buy100:$("buyMode100Btn"),reset:$("resetBtn"),summary:$("buyAllSummary"),currentLevel:$("currentLevel"),currentLevelName:$("currentLevelName"),nextLevel:$("nextLevel"),levelProgress:$("levelProgress"),progressBar:$("progressBar"),levelList:$("levelList"),rawClicks:$("rawClicks"),statPerClick:$("statPerClick"),statPerSec:$("statPerSec"),clicksPerMin:$("clicksPerMin"),hoursPlayed:$("hoursPlayed"),sessionTime:$("sessionTime"),totalUpgrades:$("totalUpgradesStat"),buyModeReadout:$("buyModeReadout"),shop:$("shop"),floating:$("floatingLayer"),tamper:$("tamperOverlay"),tamperMsg:$("tamperMessage"),tamperOk:$("tamperAcknowledgeBtn"),warning:$("contentWarningOverlay"),warningToggle:$("dismissWarningToggle"),warningBtn:$("contentWarningBtn")};

let autoCarry=0n,clickTimes=[],sessionStart=Date.now(),lastLevel=-1,saveTick=0,shopBuilt=false;
const shopNodes=new Map();
let state=freshState();

function freshState(){return{score10:0n,perClick:BASE_PER_CLICK,upgradesOwned:0n,selectedSkin:"epstein",safeMode:false,buyMode:1n,rawClicks:0,totalPlayMs:0,lastBulkSummary:"BUY ALL READY.",upgrades:UPGRADES.map(u=>({id:u[0],name:u[1],initialCost:u[2],cost:u[2],add:u[3],owned:0n,scaleNum:u[4],scaleDen:100n}))};}
function commas(v){const s=(v<0n?-v:v).toString();return (v<0n?"-":"")+s.replace(/\B(?=(\d{3})+(?!\d))/g,",");}
function named(v){const map=[[1000000000000n,"trillion"],[1000000000n,"billion"],[1000000n,"million"],[1000n,"thousand"]];for(const [amt,name] of map){if(v>=amt){const w=v/amt;const d=w<100n?Number((v%amt)*10n/amt):0;return d?`${w}.${d} ${name}`:`${w} ${name}`;}}return commas(v);}
function fmt10(v){const whole=v/SCORE_STEP,t=v%SCORE_STEP;return whole>=1000000n?(t?`${named(whole)} ${t}/10`:named(whole)):`${commas(whole)}.${t}`;}
function fmtPerSec(v){const whole=v/SCORE_STEP,t=v%SCORE_STEP;return whole>=1000000n?(t?`${named(whole)} ${t}/10`:named(whole)):`${commas(whole)}.${t}`;}
function fmtTime(ms){const h=Math.floor(ms/3600000),m=Math.floor((ms%3600000)/60000),s=Math.floor((ms%60000)/1000);return`${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`;}
function seal(t){let h=2166136261n;for(let i=0;i<t.length;i+=1){h^=BigInt(t.charCodeAt(i));h=(h*16777619n)&0xffffffffn;}return h.toString(16).padStart(8,"0");}
function nextCost(cost,u){const scaled=(cost*u.scaleNum)/u.scaleDen;return scaled>cost?scaled:cost+1n;}
function costForOwned(u,owned){let c=u.initialCost;for(let i=0n;i<owned;i+=1n)c=nextCost(c,u);return c;}
function derived(upgrades){let perClick=BASE_PER_CLICK,owned=0n;for(const u of upgrades){perClick+=u.add*u.owned;owned+=u.owned;}return{perClick,owned};}
function savePayload(){return{score10:state.score10.toString(),perClick:state.perClick.toString(),upgradesOwned:state.upgradesOwned.toString(),selectedSkin:state.selectedSkin,safeMode:state.safeMode,buyMode:state.buyMode.toString(),rawClicks:state.rawClicks,totalPlayMs:state.totalPlayMs+(Date.now()-sessionStart),upgrades:state.upgrades.map(u=>({id:u.id,owned:u.owned.toString(),cost:u.cost.toString()}))};}
function save(){try{const payload=savePayload();localStorage.setItem(SAVE_KEY,JSON.stringify({v:SAVE_VERSION,payload,seal:seal(JSON.stringify(payload))}));}catch{}}
function parseBig(v){try{return typeof v==="string"&&/^-?\d+$/.test(v)?BigInt(v):null;}catch{return null;}}
function restore(raw){try{const parsed=JSON.parse(raw);if(!parsed||parsed.v!==SAVE_VERSION||parsed.seal!==seal(JSON.stringify(parsed.payload)))return false;const p=parsed.payload;const score10=parseBig(p.score10),perClick=parseBig(p.perClick),upgradesOwned=parseBig(p.upgradesOwned),buyMode=parseBig(p.buyMode);if(score10===null||perClick===null||upgradesOwned===null||buyMode===null||!BUY_MODES.includes(buyMode))return false;const upgrades=freshState().upgrades;const map=new Map(upgrades.map(u=>[u.id,u]));for(const s of p.upgrades||[]){const u=map.get(s.id),owned=parseBig(s.owned),cost=parseBig(s.cost);if(!u||owned===null||cost===null||costForOwned(u,owned)!==cost)return false;u.owned=owned;u.cost=cost;}const d=derived(upgrades);if(d.perClick!==perClick||d.owned!==upgradesOwned)return false;state={score10,perClick,upgradesOwned,selectedSkin:SKINS.some(s=>s[0]===p.selectedSkin)?p.selectedSkin:"epstein",safeMode:!!p.safeMode,buyMode,rawClicks:Number(p.rawClicks||0),totalPlayMs:Number(p.totalPlayMs||0),lastBulkSummary:"SAVE LOADED.",upgrades};sessionStart=Date.now();return true;}catch{return false;}}
function tamper(reason){state=freshState();autoCarry=0n;sessionStart=Date.now();localStorage.removeItem(SAVE_KEY);if(el.tamperMsg)el.tamperMsg.textContent=`${reason} The save was reset to keep the game stable.`;if(el.tamper)el.tamper.hidden=false;renderAll();}
function audit(){const d=derived(state.upgrades);if(d.perClick!==state.perClick||d.owned!==state.upgradesOwned||state.score10<0n){tamper("Runtime drift detected.");return false;}return true;}
function levelReq(level){if(level<=1)return 0n;const v=BigInt(level-1);if(level<=200)return 125n*v*v*v+1800n*v*v+12000n*v;const early=levelReq(200),e=v-199n;return early+250000000n*e*e+50000000n*e*e*e;}
function levelName(level){return LEVEL_NAMES[(level-1)%LEVEL_NAMES.length];}
function currentLevel(){const score=state.score10/SCORE_STEP;let low=1,high=TOTAL_LEVELS;while(low<high){const mid=Math.floor((low+high+1)/2);if(score>=levelReq(mid))low=mid;else high=mid-1;}return low;}
function levelProgress(level){if(level>=TOTAL_LEVELS)return 100;const score=state.score10/SCORE_STEP,cur=levelReq(level),next=levelReq(level+1);return Math.max(0,Math.min(100,Number(((score-cur)*1000n)/(next-cur))/10));}
function effectiveSkin(){if(!state.safeMode)return state.selectedSkin;return state.selectedSkin==="epstein"||state.selectedSkin==="epstein2"?"mrbeast":state.selectedSkin;}
function renderSkin(){const found=SKINS.find(s=>s[0]===effectiveSkin())||SKINS[0];document.title="Epstein Clicker - Play";if(el.pageTitle)el.pageTitle.textContent="Epstein Clicker - Play";el.safeModeBadge.textContent=`SAFE MODE: ${state.safeMode?"ON":"OFF"}`;el.subjectHeading.textContent="EPSTEIN CLICKER";el.clickBtn.src=found[2];el.clickBtn.alt=`${found[1]} portrait`;el.skinSelect.value=state.selectedSkin;el.safeToggle.checked=state.safeMode;}
function renderBuyMode(){[[el.buy1,1n],[el.buy10,10n],[el.buy100,100n]].forEach(([b,m])=>b.classList.toggle("is-active",state.buyMode===m));el.buyModeReadout.textContent=`${state.buyMode}X`;}
function renderStats(){el.score.textContent=fmt10(state.score10);el.perClick.textContent=named(state.perClick);el.perSec.textContent=fmtPerSec(state.perClick);el.upgradeCount.textContent=commas(state.upgradesOwned);el.rawClicks.textContent=String(state.rawClicks);el.statPerClick.textContent=named(state.perClick);el.statPerSec.textContent=fmtPerSec(state.perClick);el.totalUpgrades.textContent=commas(state.upgradesOwned);const sessionMs=Date.now()-sessionStart,totalMs=state.totalPlayMs+sessionMs;el.hoursPlayed.textContent=(totalMs/3600000).toFixed(2);el.sessionTime.textContent=fmtTime(sessionMs);el.clicksPerMin.textContent=sessionMs>0?(state.rawClicks/(sessionMs/60000)).toFixed(1):"0.0";}
function renderLevels(){const lvl=currentLevel(),next=lvl>=TOTAL_LEVELS?0n:levelReq(lvl+1),progress=levelProgress(lvl);el.currentLevel.textContent=String(lvl);el.currentLevelName.textContent=levelName(lvl);el.nextLevel.textContent=lvl>=TOTAL_LEVELS?"MAX":named(next);el.levelProgress.textContent=`${progress.toFixed(1)}%`;el.progressBar.style.width=`${progress}%`;if(lastLevel!==lvl){lastLevel=lvl;el.levelList.innerHTML="";const end=Math.min(TOTAL_LEVELS,lvl+LEVEL_PREVIEW_COUNT-1);for(let i=lvl;i<=end;i+=1){const row=document.createElement("div");row.className=`level-item${i===lvl?" active":""}`;row.innerHTML=`<span>${i}. ${levelName(i)}</span><strong>${i>=TOTAL_LEVELS?"MAX":named(levelReq(i+1))}</strong>`;el.levelList.appendChild(row);}}}
function setSummary(text){state.lastBulkSummary=text;el.summary.textContent=text;}
function purchasePlan(u,balance10,count){let spent10=0n,bought=0n,cost=u.cost,steps=0;while(bought<count&&steps<MAX_STEPS){const c10=cost*SCORE_STEP;if(spent10+c10>balance10)break;spent10+=c10;cost=nextCost(cost,u);bought+=1n;steps+=1;}return{count:bought,spent10,nextCost:cost};}
function maxPlan(u,balance10){let spent10=0n,bought=0n,cost=u.cost,steps=0;while(steps<MAX_STEPS){const c10=cost*SCORE_STEP;if(spent10+c10>balance10)break;spent10+=c10;cost=nextCost(cost,u);bought+=1n;steps+=1;}return{count:bought,spent10,nextCost:cost};}
function applyPlan(u,plan){if(plan.count<=0n)return false;state.score10-=plan.spent10;u.owned+=plan.count;u.cost=plan.nextCost;state.perClick+=u.add*plan.count;state.upgradesOwned+=plan.count;return true;}
function buildShop(){el.shop.innerHTML="";shopNodes.clear();for(const u of state.upgrades){const row=document.createElement("article");row.className="shop-row";row.innerHTML=`<div class=\"shop-copy\"><h3>${u.name}</h3><p></p></div><div class=\"shop-actions\"><button type=\"button\"></button><button type=\"button\"></button></div>`;const p=row.querySelector("p"),buttons=row.querySelectorAll("button");buttons[0].addEventListener("click",()=>buyUpgrade(u.id,state.buyMode));buttons[1].addEventListener("click",()=>buyUpgradeMax(u.id));el.shop.appendChild(row);shopNodes.set(u.id,{p,buy:buttons[0],max:buttons[1]});}shopBuilt=true;refreshShop();}
function refreshShop(){for(const u of state.upgrades){const n=shopNodes.get(u.id);if(!n)continue;const plan=purchasePlan(u,state.score10,state.buyMode),m=maxPlan(u,state.score10);n.p.innerHTML=`Owned: x${commas(u.owned)}<br>+${named(u.add)} per click<br>Cost: ${named(u.cost)}`;n.buy.textContent=`BUY ${state.buyMode}X`;n.max.textContent=m.count>0n?`MAX (${commas(m.count)})`:"MAX";n.buy.disabled=plan.count===0n;n.max.disabled=m.count===0n;}}
function buyUpgrade(id,count){const u=state.upgrades.find(x=>x.id===id);if(!u)return;const plan=purchasePlan(u,state.score10,count);if(!applyPlan(u,plan))return;setSummary(`BOUGHT ${plan.count} ${u.name.toUpperCase()}.`);renderAll();save();}
function buyUpgradeMax(id){const u=state.upgrades.find(x=>x.id===id);if(!u)return;const plan=maxPlan(u,state.score10);if(!applyPlan(u,plan))return;setSummary(`MAX BOUGHT ${plan.count} ${u.name.toUpperCase()}.`);renderAll();save();}
function buyAll(){let total=0n;for(const u of state.upgrades){const plan=purchasePlan(u,state.score10,state.buyMode);if(applyPlan(u,plan))total+=plan.count;}if(total===0n){setSummary("NOTHING AFFORDABLE.");refreshShop();return;}setSummary(`BUY ALL BOUGHT ${total} UPGRADES.`);renderAll();save();}
function floatText(text,x,y){const d=document.createElement("div");d.className="float-text";d.textContent=text;d.style.left=`${x}px`;d.style.top=`${y}px`;el.floating.appendChild(d);setTimeout(()=>d.remove(),740);}
function noteClick(now){clickTimes.push(now);clickTimes=clickTimes.filter(t=>t>=now-4000);if(clickTimes.length>140){tamper("Click rate was too high.");return false;}return true;}
function clickCenter(){const r=el.clickBtn.getBoundingClientRect();return{x:r.left+r.width/2,y:r.top+r.height/2};}
function doClick(point){if(!audit()||!noteClick(performance.now()))return;state.score10+=state.perClick*SCORE_STEP;state.rawClicks+=1;floatText(`+${named(state.perClick)}`,point.x,point.y);el.clickBtn.classList.add("is-pressed");setTimeout(()=>el.clickBtn.classList.remove("is-pressed"),110);renderStats();renderLevels();refreshShop();}
function renderAll(){renderSkin();renderBuyMode();renderStats();renderLevels();if(!shopBuilt)buildShop();else refreshShop();el.summary.textContent=state.lastBulkSummary;}

SKINS.forEach(s=>{const i=new Image();i.src=s[2];const o=document.createElement("option");o.value=s[0];o.textContent=s[1];el.skinSelect.appendChild(o);});
const saved=localStorage.getItem(SAVE_KEY);if(saved&&!restore(saved))tamper("Save integrity check failed.");
renderAll();
el.clickBtn.addEventListener("click",e=>{if(!e.isTrusted){tamper("Synthetic click blocked.");return;}doClick({x:e.clientX,y:e.clientY});});
document.addEventListener("keydown",e=>{if(!e.isTrusted)return;const t=e.target;if(t instanceof HTMLElement&&(t.tagName==="INPUT"||t.tagName==="SELECT"||t.tagName==="TEXTAREA"||t.isContentEditable))return;if(e.code==="Space"){e.preventDefault();doClick(clickCenter());}if(e.code==="KeyB"){e.preventDefault();buyAll();}if(e.code==="KeyS"){e.preventDefault();state.safeMode=!state.safeMode;renderSkin();save();}});
el.skinSelect.addEventListener("change",()=>{state.selectedSkin=el.skinSelect.value;renderSkin();save();});
el.safeToggle.addEventListener("change",()=>{state.safeMode=el.safeToggle.checked;renderSkin();save();});
el.buy1.addEventListener("click",()=>{state.buyMode=1n;renderBuyMode();refreshShop();});
el.buy10.addEventListener("click",()=>{state.buyMode=10n;renderBuyMode();refreshShop();});
el.buy100.addEventListener("click",()=>{state.buyMode=100n;renderBuyMode();refreshShop();});
el.buyAll.addEventListener("click",buyAll);
el.reset.addEventListener("click",()=>{state=freshState();autoCarry=0n;sessionStart=Date.now();lastLevel=-1;localStorage.removeItem(SAVE_KEY);renderAll();});
el.tamperOk.addEventListener("click",()=>{el.tamper.hidden=true;});
el.warningBtn.addEventListener("click",()=>{if(el.warningToggle.checked)localStorage.setItem(WARNING_KEY,"1");el.warning.hidden=true;});
if(localStorage.getItem(WARNING_KEY)==="1")el.warning.hidden=true;
window.addEventListener("beforeunload",save);
setInterval(()=>{if(!audit())return;autoCarry+=state.perClick;const addNow=autoCarry/AUTO_TICKS_PER_SEC;autoCarry%=AUTO_TICKS_PER_SEC;if(addNow>0n){state.score10+=addNow;renderStats();renderLevels();refreshShop();}},50);
setInterval(()=>{saveTick+=1;renderStats();if(saveTick>=4){save();saveTick=0;}},500);
setInterval(()=>{audit();},2500);
